### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by RyanZim** [comment]
Why is this needed? In what theoretical case would the behavior be different on a different architecture, and therefore warrant testing on it?

**Comment by dineshks1** [comment]
This is a part of Ubuntu distribution for ppc64le architecture. It will help us to simplify testing later when distributions are re-building and re-releasing.

**Comment by RyanZim** [comment]
Sorry, but I'm not understanding.

> This is a part of Ubuntu distribution for ppc64le architecture.

What is "this"?

> It will help us to simplify testing later

Does "us" refer to your team, or myself as maintainer of `universalify`?

**Comment by dineshks1** [comment]
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by dineshks1** [comment]
Please review this merge.

**Pull request closed without merging**
